-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg42cxvty82Oa2t2OK
8Jw33FifECHTNCiVxKyjeMwAGpygCgYIKoZIzj0DAQehRANCAARHLoTeZX9VCro0
1GexhSxgV36qN+hGWDPo9sZ0SHEKEcEK05iTZMCoq+QidofHkQVrgPgDfqCj0Awh
UMza0C//
-----END PRIVATE KEY-----